// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKqIQMmBxd7DJm-epAXEOfOPylZ-85o-Q',
    appId: '1:531035948682:web:bd925885ba19f5eda48f73',
    messagingSenderId: '531035948682',
    projectId: 'first-shrawan-ba41b',
    authDomain: 'first-shrawan-ba41b.firebaseapp.com',
    storageBucket: 'first-shrawan-ba41b.appspot.com',
    measurementId: 'G-KHTLBFREJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvWciIrRvW9ad1jwkDGMCiXJFU5oqB01A',
    appId: '1:531035948682:android:e4eef2137a8083ada48f73',
    messagingSenderId: '531035948682',
    projectId: 'first-shrawan-ba41b',
    storageBucket: 'first-shrawan-ba41b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChtwrOMjWeerfPDEUOln3CqGbS3muevnU',
    appId: '1:531035948682:ios:369267d639675d26a48f73',
    messagingSenderId: '531035948682',
    projectId: 'first-shrawan-ba41b',
    storageBucket: 'first-shrawan-ba41b.appspot.com',
    iosBundleId: 'com.example.firstMadness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChtwrOMjWeerfPDEUOln3CqGbS3muevnU',
    appId: '1:531035948682:ios:369267d639675d26a48f73',
    messagingSenderId: '531035948682',
    projectId: 'first-shrawan-ba41b',
    storageBucket: 'first-shrawan-ba41b.appspot.com',
    iosBundleId: 'com.example.firstMadness',
  );
}
